/*
 * generated by Xtext 2.9.2
 */
package net.dreiucker


/**
 * Use this class to register components to be used at runtime / without the Equinox extension registry.
 */
class DecDescLanguageRuntimeModule extends AbstractDecDescLanguageRuntimeModule {
}
